baseurl: 'www.tampashutter.net'
copyright: '© Ayoub Abedrabbo'
enablerobotstxt: true
languagecode: 'en-us'
languages:
  en:
    menu:
      main:
        - identifier: 'home'
          name: 'Home'
          url: '/'
          weight: 10
        - identifier: 'aboutme'
          name: 'About Me'
          url: '/aboutme/'
          weight: 30
        - identifier: 'gallery'
          name: 'Gallery'
          url: '/gallery/'
          weight: 40
        - identifier: 'contactme'
          name: 'Contact Me @ Telegram'
          url: 'https://t.me/AyoubAb1'
          weight: 40
        - identifier: 'Services'
          name: 'Services'
          url: '/services/'
          weight: 50
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
outputs:
  home:
    - 'html'
    - 'json'
    - 'rss'
paginate: 50
taxonomies:
  author: 'authors'
  category: 'categories'
  series: 'series'
  tag: 'tags'
timezone: 'America/New_York'
titlecasestyle: 'Go'
module:
  imports:
    - path: github.com/willfaught/paige
